"""Command-line entry point for generating pymatgen JSON crystal structures."""

from __future__ import annotations

import argparse
import csv
from collections import Counter
from concurrent.futures import ProcessPoolExecutor
import json
import math
from pathlib import Path
import random
from typing import Mapping, Sequence

from pymatgen.core import Structure

from crystal_llm.chemistry import SAMPLERS, Strategy, load_strategy, make_ion
from crystal_llm.filters import (
    StructureDeduplicator,
    load_known_formulas,
    reduced_formula,
    structure_signature,
    validate_structure,
)
from crystal_llm.templates import BUILDERS, TEMPLATE_WEIGHTS, Candidate


def parse_args(argv: Sequence[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Generate candidate crystal structures in pymatgen JSON format.")
    parser.add_argument("--output", default="input.json", help="Output JSON path.")
    parser.add_argument("--report", default=None, help="Optional generation report JSON path.")
    parser.add_argument("--target-count", type=int, default=1000, help="Number of structures to write.")
    parser.add_argument("--candidate-multiplier", type=int, default=4, help="Candidate pool size relative to target.")
    parser.add_argument("--seed", type=int, default=20260501, help="Random seed.")
    parser.add_argument("--training-data", default=None, help="Optional training CSV for composition novelty filtering.")
    parser.add_argument("--strategy", default=None, help="Optional strategy JSON generated by an LLM/agent.")
    parser.add_argument("--max-sites", type=int, default=80, help="Reject structures with more sites than this.")
    parser.add_argument("--max-per-formula", type=int, default=1, help="Preferred max selected structures per reduced formula.")
    parser.add_argument("--allow-known-compositions", action="store_true", help="Do not penalize formulas seen in training data.")
    parser.add_argument("--jobs", type=int, default=1, help="Parallel worker processes for candidate collection.")
    parser.add_argument("--candidate-pool-output", default=None, help="Optional path to write the pre-final candidate pool.")
    parser.add_argument("--candidate-pool-report", default=None, help="Optional report path for --candidate-pool-output.")
    parser.add_argument("--candidate-pool-only", action="store_true", help="Write the pre-final candidate pool to --output and skip final selection.")
    parser.add_argument(
        "--skip-random-generation",
        action="store_true",
        help="Skip random template sampling and use only strategy-provided elite replay/formula probes.",
    )
    parser.add_argument(
        "--formula-probes-only",
        action="store_true",
        help="Only build explicit strategy formula_probes; skip random generation and elite replay.",
    )
    return parser.parse_args(argv)


def load_strategy_raw(path: str | None) -> dict:
    if not path:
        return {}
    strategy_path = Path(path)
    if not strategy_path.exists():
        raise FileNotFoundError(f"strategy file not found: {path}")
    with strategy_path.open("r", encoding="utf-8") as handle:
        raw = json.load(handle)
    if not isinstance(raw, dict):
        raise ValueError("strategy JSON must be an object")
    return raw


def load_strategy_file(path: str | None) -> Strategy:
    raw = load_strategy_raw(path)
    if not raw:
        return Strategy()
    return load_strategy(raw)


def load_elite_replay(raw_strategy: dict, max_sites: int) -> list[Candidate]:
    config = raw_strategy.get("elite_replay", {})
    if not isinstance(config, dict) or not config.get("enabled", False):
        return []

    try:
        e_hull_max = float(config.get("e_hull_max", 0.0))
    except (TypeError, ValueError):
        e_hull_max = 0.0
    try:
        max_count = int(config.get("max_count", 0))
    except (TypeError, ValueError):
        max_count = 0
    try:
        max_per_formula = int(config.get("max_per_formula", 1))
    except (TypeError, ValueError):
        max_per_formula = 1
    max_per_formula = max(1, max_per_formula)

    sources = config.get("sources", [])
    if not isinstance(sources, list):
        return []
    exclude_formulas_raw = config.get("exclude_formulas", [])
    if isinstance(exclude_formulas_raw, str):
        exclude_formulas = {exclude_formulas_raw}
    elif isinstance(exclude_formulas_raw, list):
        exclude_formulas = {str(item) for item in exclude_formulas_raw}
    else:
        exclude_formulas = set()

    records: list[tuple[float, dict, list, int, dict[str, str]]] = []

    for source in sources:
        if not isinstance(source, dict):
            continue
        input_path = Path(str(source.get("input", "")))
        ranked_path = Path(str(source.get("ranked_e_hull", "")))
        if not input_path.exists() or not ranked_path.exists():
            continue

        with input_path.open("r", encoding="utf-8") as handle:
            structures_raw = json.load(handle)
        if not isinstance(structures_raw, list):
            continue

        rows: list[dict[str, str]] = []
        with ranked_path.open("r", encoding="utf-8", newline="") as handle:
            reader = csv.DictReader(handle)
            rows.extend(reader)

        def e_hull_value(row: dict[str, str]) -> float:
            try:
                return float(row.get("e_hull", "inf"))
            except ValueError:
                return math.inf

        for row in sorted(rows, key=e_hull_value):
            e_hull = e_hull_value(row)
            if not e_hull < e_hull_max:
                continue
            try:
                index = int(row["index"]) - 1
            except (KeyError, TypeError, ValueError):
                continue
            if index < 0 or index >= len(structures_raw):
                continue
            records.append((e_hull, source, structures_raw, index, row))

    replay_candidates: list[Candidate] = []
    formula_counts: Counter = Counter()

    for e_hull, source, structures_raw, index, row in sorted(records, key=lambda item: item[0]):
        structure = Structure.from_dict(structures_raw[index])
        validation = validate_structure(structure, max_sites=max_sites)
        if not validation.ok:
            continue
        formula = reduced_formula(structure)
        if formula in exclude_formulas:
            continue
        if formula_counts[formula] >= max_per_formula:
            continue
        formula_counts[formula] += 1

        template = row.get("template_guess") or structure.properties.get("crystal_llm_template") or "unknown"
        candidate = Candidate(
            structure=structure,
            template=template,
            metadata={
                "elite_replay": "true",
                "elite_source_round": str(source.get("round", "")),
                "elite_source_index": str(index + 1),
                "elite_e_hull": e_hull,
            },
            score=100.0 - len(replay_candidates) * 0.0001,
        )
        replay_candidates.append(candidate)
        if max_count > 0 and len(replay_candidates) >= max_count:
            return replay_candidates

    return replay_candidates


def load_formula_probes(
    raw_strategy: dict,
    max_sites: int,
    base_seed: int = 0,
    known_formulas: set[str] | None = None,
) -> list[Candidate]:
    """Load explicit role-constrained prototype probes from strategy JSON."""

    probes = raw_strategy.get("formula_probes", [])
    if not isinstance(probes, list):
        return []

    def parse_role(value: object) -> tuple[str, int] | None:
        if isinstance(value, Mapping):
            element = value.get("element")
            oxidation_state = value.get("oxidation_state", value.get("oxi"))
            if element is None or oxidation_state is None:
                return None
            try:
                return str(element), int(oxidation_state)
            except (TypeError, ValueError):
                return None
        if isinstance(value, Sequence) and not isinstance(value, str) and len(value) >= 2:
            try:
                return str(value[0]), int(value[1])
            except (TypeError, ValueError):
                return None
        return None

    candidates: list[Candidate] = []
    seen_formulas: set[str] = set()

    for probe_index, probe in enumerate(probes):
        if not isinstance(probe, Mapping):
            continue
        template = str(probe.get("template", ""))
        builder = BUILDERS.get(template)
        roles_raw = probe.get("roles", {})
        if builder is None or not isinstance(roles_raw, Mapping):
            continue

        roles = {}
        for role, value in roles_raw.items():
            parsed = parse_role(value)
            if parsed is None:
                roles = {}
                break
            element, oxidation_state = parsed
            roles[str(role)] = make_ion(element, oxidation_state)
        if not roles:
            continue

        rng = random.Random(base_seed + 9_100_003 + probe_index * 131_071)
        try:
            candidate = builder(roles, rng)
        except Exception:
            continue

        validation = validate_structure(candidate.structure, max_sites=max_sites)
        if not validation.ok:
            continue
        formula = reduced_formula(candidate.structure)
        if known_formulas and formula in known_formulas:
            continue
        if formula in seen_formulas:
            continue
        seen_formulas.add(formula)
        candidate.template = template
        candidate.metadata.update(
            {
                "formula_probe": "true",
                "formula_probe_id": str(probe.get("id", f"probe_{probe_index:03d}")),
                "formula_probe_family": str(probe.get("family", "")),
            }
        )
        candidate.score = 95.0 - len(candidates) * 0.001
        candidates.append(candidate)

    return candidates


def choose_template(rng: random.Random, strategy: Strategy) -> str:
    names = list(BUILDERS)
    target_counts = strategy.template_target_counts
    if target_counts:
        omitted = [name for name in names if name not in target_counts]
        other_weight = float(target_counts.get("other_templates_fill", 0))
        if omitted and other_weight > 0:
            other_weight /= len(omitted)
        weights = [
            max(0.01, float(target_counts.get(name, other_weight)))
            for name in names
        ]
        return rng.choices(names, weights=weights, k=1)[0]

    weights: list[float] = []
    for name in names:
        weight = TEMPLATE_WEIGHTS[name]
        if strategy.focus_templates and name in strategy.focus_templates:
            weight *= 3.0
        elif strategy.focus_templates:
            weight *= 0.45
        weights.append(weight)
    return rng.choices(names, weights=weights, k=1)[0]


def scaled_template_targets(strategy: Strategy, target_count: int) -> dict[str, int]:
    targets = {
        template: count
        for template, count in strategy.template_target_counts.items()
        if template in BUILDERS and count > 0
    }
    total = sum(targets.values())
    if not targets or total <= target_count:
        return targets

    scale = target_count / total
    scaled = {template: max(1, int(count * scale)) for template, count in targets.items()}
    overflow = sum(scaled.values()) - target_count
    if overflow <= 0:
        return scaled

    for template, _ in sorted(targets.items(), key=lambda item: item[1], reverse=True):
        if overflow <= 0:
            break
        removable = min(overflow, scaled[template] - 1)
        if removable <= 0:
            continue
        scaled[template] -= removable
        overflow -= removable
    return scaled


def template_max_counts(strategy: Strategy) -> dict[str, int]:
    return {
        template: count
        for template, count in strategy.template_max_counts.items()
        if template in BUILDERS and count > 0
    }


def trim_candidate_pool(
    candidates: list[Candidate],
    pool_target: int,
    strategy: Strategy,
    target_count: int,
    candidate_multiplier: int,
) -> list[Candidate]:
    if len(candidates) <= pool_target:
        return candidates

    sorted_candidates = sorted(candidates, key=lambda item: item.score, reverse=True)
    template_targets = scaled_template_targets(strategy, target_count)
    template_caps = template_max_counts(strategy)
    if not template_targets:
        return sorted_candidates[:pool_target]

    selected: list[Candidate] = []
    selected_ids: set[int] = set()

    def add(candidate: Candidate) -> bool:
        candidate_id = id(candidate)
        if candidate_id in selected_ids:
            return False
        selected.append(candidate)
        selected_ids.add(candidate_id)
        return True

    reserve_multiplier = max(1, candidate_multiplier)
    for template, target in template_targets.items():
        reserve = min(pool_target, max(target, target * reserve_multiplier))
        kept = 0
        for candidate in sorted_candidates:
            if kept >= reserve:
                break
            if candidate.template != template:
                continue
            if add(candidate):
                kept += 1

    for candidate in sorted_candidates:
        if len(selected) >= pool_target:
            break
        add(candidate)

    return selected[:pool_target]


def score_candidate(candidate: Candidate, known_formulas: set[str], rng: random.Random, allow_known: bool) -> float:
    structure = candidate.structure
    validation = validate_structure(structure)
    formula = reduced_formula(structure)
    score = TEMPLATE_WEIGHTS.get(candidate.template, 0.5)

    if formula in known_formulas and not allow_known:
        score -= 0.75
    else:
        score += 0.30

    # Prefer geometries that leave neither implausibly short contacts nor huge voids.
    if validation.min_distance >= 1.0:
        score += min(0.25, (validation.min_distance - 1.0) * 0.15)
    if 7.0 <= validation.volume_per_atom <= 24.0:
        score += 0.18
    elif 5.0 <= validation.volume_per_atom <= 29.5:
        score += 0.08

    tolerance = candidate.metadata.get("tolerance_factor")
    if isinstance(tolerance, float):
        if 0.82 <= tolerance <= 1.08:
            score += 0.45
        elif 0.75 <= tolerance <= 1.15:
            score += 0.20
        else:
            score -= 0.20

    # Small deterministic jitter spreads ties without dominating chemistry.
    return score + rng.uniform(0.0, 0.03)


def make_candidate(template: str, rng: random.Random, strategy: Strategy) -> Candidate:
    ions = SAMPLERS[template](rng, strategy, template)
    return BUILDERS[template](ions, rng)


def _collect_candidate_shard(
    seed: int,
    attempts_target: int,
    strategy: Strategy,
    known_formulas: set[str],
    max_sites: int,
    allow_known: bool,
) -> tuple[list[Candidate], Counter]:
    rng = random.Random(seed)
    candidates: list[Candidate] = []
    seen_signatures: set[tuple] = set()
    reject_reasons: Counter = Counter()

    for _ in range(attempts_target):
        template = choose_template(rng, strategy)

        try:
            candidate = make_candidate(template, rng, strategy)
        except Exception as exc:
            reject_reasons[f"build_error:{type(exc).__name__}"] += 1
            continue

        validation = validate_structure(candidate.structure, max_sites=max_sites)
        if not validation.ok:
            for reason in validation.reasons:
                reject_reasons[reason] += 1
            continue

        formula = reduced_formula(candidate.structure)
        if known_formulas and formula in known_formulas and not allow_known:
            if rng.random() < 0.94:
                reject_reasons["known_formula"] += 1
                continue

        signature = structure_signature(candidate.structure)
        if signature in seen_signatures:
            reject_reasons["duplicate"] += 1
            continue
        seen_signatures.add(signature)

        candidate.score = score_candidate(candidate, known_formulas, rng, allow_known)
        candidates.append(candidate)

    reject_reasons["attempts"] = attempts_target
    return candidates, reject_reasons


def collect_candidates(args: argparse.Namespace, strategy: Strategy, known_formulas: set[str]) -> tuple[list[Candidate], Counter]:
    rng = random.Random(args.seed)
    pool_target = max(args.target_count * args.candidate_multiplier, args.target_count)
    max_attempts = max(pool_target * 30, 30000)
    candidates: list[Candidate] = []
    seen_signatures: set[tuple] = set()
    reject_reasons: Counter = Counter()

    attempts = 0
    while len(candidates) < pool_target and attempts < max_attempts:
        attempts += 1
        template = choose_template(rng, strategy)

        try:
            candidate = make_candidate(template, rng, strategy)
        except Exception as exc:
            reject_reasons[f"build_error:{type(exc).__name__}"] += 1
            continue

        validation = validate_structure(candidate.structure, max_sites=args.max_sites)
        if not validation.ok:
            for reason in validation.reasons:
                reject_reasons[reason] += 1
            continue

        formula = reduced_formula(candidate.structure)
        if known_formulas and formula in known_formulas and not args.allow_known_compositions:
            # Keep a small tail of known compositions for stability, but bias hard
            # toward composition novelty because S.U.N. is divided by total output.
            if rng.random() < 0.94:
                reject_reasons["known_formula"] += 1
                continue

        signature = structure_signature(candidate.structure)
        if signature in seen_signatures:
            reject_reasons["duplicate"] += 1
            continue
        seen_signatures.add(signature)

        candidate.score = score_candidate(candidate, known_formulas, rng, args.allow_known_compositions)
        candidates.append(candidate)

    reject_reasons["attempts"] = attempts
    return candidates, reject_reasons


def collect_candidates_parallel(
    args: argparse.Namespace,
    strategy: Strategy,
    known_formulas: set[str],
) -> tuple[list[Candidate], Counter]:
    pool_target = max(args.target_count * args.candidate_multiplier, args.target_count)
    max_attempts = max(pool_target * 30, 30000)
    jobs = max(1, min(args.jobs, max_attempts))
    attempts_per_job = max(50, math.ceil(pool_target * 2 / jobs))

    candidates: list[Candidate] = []
    seen_signatures: set[tuple] = set()
    reject_reasons: Counter = Counter()
    attempts_done = 0
    batch_index = 0

    print(
        f"collecting candidates with {jobs} workers, target pool {pool_target}, "
        f"up to {max_attempts} attempts",
        flush=True,
    )
    with ProcessPoolExecutor(max_workers=jobs) as executor:
        while len(candidates) < pool_target and attempts_done < max_attempts:
            remaining = max_attempts - attempts_done
            active_jobs = min(jobs, math.ceil(remaining / attempts_per_job))
            shard_args = []
            for shard in range(active_jobs):
                attempts = min(attempts_per_job, remaining - attempts_per_job * shard)
                if attempts <= 0:
                    continue
                shard_args.append(
                    (
                        args.seed + 1_000_003 * (batch_index * jobs + shard),
                        attempts,
                        strategy,
                        known_formulas,
                        args.max_sites,
                        args.allow_known_compositions,
                    )
                )

            for shard_candidates, shard_rejects in executor.map(_collect_candidate_shard_unpack, shard_args):
                reject_reasons.update(shard_rejects)
                for candidate in shard_candidates:
                    signature = structure_signature(candidate.structure)
                    if signature in seen_signatures:
                        reject_reasons["duplicate"] += 1
                        continue
                    seen_signatures.add(signature)
                    candidates.append(candidate)

            batch_attempts = sum(item[1] for item in shard_args)
            attempts_done += batch_attempts
            batch_index += 1
            print(
                f"candidate batch {batch_index}: {len(candidates)}/{pool_target} "
                f"after {attempts_done} attempts",
                flush=True,
            )

    candidates = trim_candidate_pool(
        candidates,
        pool_target,
        strategy,
        args.target_count,
        args.candidate_multiplier,
    )

    reject_reasons["attempts"] = attempts_done
    return candidates, reject_reasons


def _collect_candidate_shard_unpack(args: tuple) -> tuple[list[Candidate], Counter]:
    return _collect_candidate_shard(*args)


def select_final(
    candidates: list[Candidate],
    target_count: int,
    max_per_formula: int,
    strategy: Strategy,
) -> list[Candidate]:
    candidates = sorted(candidates, key=lambda item: item.score, reverse=True)
    selected: list[Candidate] = []
    formula_counts: Counter = Counter()
    template_counts: Counter = Counter()
    final_seen = StructureDeduplicator()
    soft_template_cap = max(50, int(target_count * 0.25))
    template_targets = scaled_template_targets(strategy, target_count)
    template_caps = template_max_counts(strategy)

    def under_strategy_cap(template: str) -> bool:
        cap = template_caps.get(template)
        return cap is None or template_counts[template] < cap

    def try_add(candidate: Candidate, *, formula_limit: int, enforce_template_cap: bool) -> bool:
        formula = reduced_formula(candidate.structure)
        if formula_counts[formula] >= formula_limit:
            return False
        if enforce_template_cap:
            if template_caps:
                if not under_strategy_cap(candidate.template):
                    return False
            elif template_counts[candidate.template] >= soft_template_cap:
                return False
        if not final_seen.add(candidate.structure):
            return False
        selected.append(candidate)
        formula_counts[formula] += 1
        template_counts[candidate.template] += 1
        return True

    for candidate in candidates:
        if len(selected) >= target_count:
            break
        if candidate.metadata.get("elite_replay") != "true":
            continue
        try_add(candidate, formula_limit=max_per_formula, enforce_template_cap=False)

    for template, target in template_targets.items():
        for candidate in candidates:
            if len(selected) >= target_count or template_counts[template] >= target:
                break
            if candidate.template != template:
                continue
            try_add(candidate, formula_limit=max_per_formula, enforce_template_cap=True)

    for template in strategy.fallback_template_order:
        if len(selected) >= target_count:
            break
        if template not in BUILDERS:
            continue
        for candidate in candidates:
            if len(selected) >= target_count or not under_strategy_cap(template):
                break
            if candidate.template != template:
                continue
            try_add(candidate, formula_limit=max_per_formula, enforce_template_cap=True)

    for candidate in candidates:
        if len(selected) >= target_count:
            break
        enforce_cap = bool(template_caps) or not template_targets
        try_add(candidate, formula_limit=max_per_formula, enforce_template_cap=enforce_cap)

    if len(selected) < target_count:
        for candidate in candidates:
            if len(selected) >= target_count:
                break
            try_add(candidate, formula_limit=max(3, max_per_formula), enforce_template_cap=False)

    return selected[:target_count]


def write_outputs(
    args: argparse.Namespace,
    selected: list[Candidate],
    known_formulas: set[str],
    rejects: Counter,
    strategy: Strategy,
) -> None:
    output_path = Path(args.output)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    structures_payload = []
    for index, candidate in enumerate(selected):
        structure_dict = candidate.structure.as_dict()
        properties = dict(structure_dict.get("properties") or {})
        properties.update(
            {
                "crystal_llm_selection_index": index,
                "crystal_llm_template": candidate.template,
                "crystal_llm_score": round(candidate.score, 6),
                "crystal_llm_metadata": dict(candidate.metadata),
            }
        )
        structure_dict["properties"] = properties
        structures_payload.append(structure_dict)
    with output_path.open("w", encoding="utf-8") as handle:
        json.dump(structures_payload, handle, ensure_ascii=False, indent=2)

    report_path = Path(args.report) if args.report else output_path.with_suffix(".report.json")
    report_path.parent.mkdir(parents=True, exist_ok=True)
    template_counts = Counter(candidate.template for candidate in selected)
    formulas = [reduced_formula(candidate.structure) for candidate in selected]
    report = {
        "requested_count": args.target_count,
        "generated_count": len(selected),
        "unique_reduced_formulas": len(set(formulas)),
        "known_training_formulas_loaded": len(known_formulas),
        "template_counts": dict(template_counts),
        "elite_replay_selected": sum(
            1 for candidate in selected if candidate.metadata.get("elite_replay") == "true"
        ),
        "formula_probe_selected": sum(
            1 for candidate in selected if candidate.metadata.get("formula_probe") == "true"
        ),
        "reject_reasons": dict(rejects),
        "top_examples": [
            {
                "formula": reduced_formula(candidate.structure),
                "template": candidate.template,
                "score": round(candidate.score, 4),
                "sites": len(candidate.structure),
            }
            for candidate in selected[:20]
        ],
    }
    template_targets = scaled_template_targets(strategy, args.target_count)
    if template_targets:
        report["selection_mode"] = "template_target_counts"
        report["template_target_counts"] = template_targets
        report["template_target_shortfalls"] = {
            template: max(0, target - template_counts.get(template, 0))
            for template, target in template_targets.items()
        }
        report["template_target_overshoots"] = {
            template: max(0, template_counts.get(template, 0) - target)
            for template, target in template_targets.items()
        }
    caps = template_max_counts(strategy)
    if caps:
        report["template_max_counts"] = caps
        report["template_max_unused"] = {
            template: max(0, cap - template_counts.get(template, 0))
            for template, cap in caps.items()
        }
    if strategy.fallback_template_order:
        report["fallback_template_order"] = list(strategy.fallback_template_order)
    with report_path.open("w", encoding="utf-8") as handle:
        json.dump(report, handle, ensure_ascii=False, indent=2)


def candidate_structure_payload(candidate: Candidate, index: int) -> dict:
    structure_dict = candidate.structure.as_dict()
    properties = dict(structure_dict.get("properties") or {})
    metadata = dict(candidate.metadata)
    metadata.setdefault("candidate_pool_index", str(index))
    properties.update(
        {
            "crystal_llm_candidate_pool_index": index,
            "crystal_llm_template": candidate.template,
            "crystal_llm_score": round(candidate.score, 6),
            "crystal_llm_metadata": metadata,
        }
    )
    structure_dict["properties"] = properties
    return structure_dict


def write_candidate_pool(
    *,
    output: str | Path,
    report: str | Path | None,
    candidates: list[Candidate],
    known_formulas: set[str],
    rejects: Counter,
    args: argparse.Namespace,
) -> None:
    output_path = Path(output)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    sorted_candidates = sorted(candidates, key=lambda item: item.score, reverse=True)
    structures_payload = [
        candidate_structure_payload(candidate, index)
        for index, candidate in enumerate(sorted_candidates)
    ]
    with output_path.open("w", encoding="utf-8") as handle:
        json.dump(structures_payload, handle, ensure_ascii=False, indent=2)

    report_path = Path(report) if report else output_path.with_suffix(".report.json")
    report_path.parent.mkdir(parents=True, exist_ok=True)
    formulas = [reduced_formula(candidate.structure) for candidate in sorted_candidates]
    template_counts = Counter(candidate.template for candidate in sorted_candidates)
    pool_report = {
        "selection_mode": "candidate_pool",
        "requested_target_count": args.target_count,
        "candidate_multiplier": args.candidate_multiplier,
        "candidate_pool_count": len(sorted_candidates),
        "unique_reduced_formulas": len(set(formulas)),
        "known_training_formulas_loaded": len(known_formulas),
        "template_counts": dict(template_counts),
        "elite_replay_loaded": sum(
            1 for candidate in sorted_candidates if candidate.metadata.get("elite_replay") == "true"
        ),
        "formula_probe_loaded": sum(
            1 for candidate in sorted_candidates if candidate.metadata.get("formula_probe") == "true"
        ),
        "reject_reasons": dict(rejects),
        "top_examples": [
            {
                "formula": reduced_formula(candidate.structure),
                "template": candidate.template,
                "score": round(candidate.score, 4),
                "sites": len(candidate.structure),
            }
            for candidate in sorted_candidates[:20]
        ],
    }
    with report_path.open("w", encoding="utf-8") as handle:
        json.dump(pool_report, handle, ensure_ascii=False, indent=2)


def main(argv: Sequence[str] | None = None) -> int:
    args = parse_args(argv)
    raw_strategy = load_strategy_raw(args.strategy)
    strategy = load_strategy(raw_strategy)
    known_formulas = load_known_formulas(args.training_data)
    if args.formula_probes_only or args.skip_random_generation:
        candidates: list[Candidate] = []
        rejects: Counter = Counter()
        if args.formula_probes_only:
            rejects["random_generation_skipped_for_formula_probes_only"] = 1
        if args.skip_random_generation:
            rejects["random_generation_skipped_by_request"] = 1
    elif args.jobs > 1:
        candidates, rejects = collect_candidates_parallel(args, strategy, known_formulas)
    else:
        candidates, rejects = collect_candidates(args, strategy, known_formulas)
    if not args.formula_probes_only:
        elite_candidates = load_elite_replay(raw_strategy, args.max_sites)
        if elite_candidates:
            candidates.extend(elite_candidates)
            rejects["elite_replay_loaded"] = len(elite_candidates)
    formula_probe_candidates = load_formula_probes(raw_strategy, args.max_sites, args.seed, known_formulas)
    if formula_probe_candidates:
        candidates.extend(formula_probe_candidates)
        rejects["formula_probe_loaded"] = len(formula_probe_candidates)

    if args.candidate_pool_output:
        write_candidate_pool(
            output=args.candidate_pool_output,
            report=args.candidate_pool_report,
            candidates=candidates,
            known_formulas=known_formulas,
            rejects=rejects,
            args=args,
        )
        print(f"candidate pool written to {args.candidate_pool_output}")

    if args.candidate_pool_only:
        write_candidate_pool(
            output=args.output,
            report=args.report,
            candidates=candidates,
            known_formulas=known_formulas,
            rejects=rejects,
            args=args,
        )
        print(f"wrote candidate pool with {len(candidates)} structures to {args.output}")
        print(f"report written to {args.report or Path(args.output).with_suffix('.report.json')}")
        return 0

    selected = select_final(candidates, args.target_count, args.max_per_formula, strategy)

    if len(selected) < args.target_count:
        raise RuntimeError(
            f"only selected {len(selected)} structures; try increasing --candidate-multiplier, "
            "--max-per-formula, or loosening strategy filters"
        )

    write_outputs(args, selected, known_formulas, rejects, strategy)
    print(f"wrote {len(selected)} structures to {args.output}")
    print(f"report written to {args.report or Path(args.output).with_suffix('.report.json')}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
